### ISSUE TITLE
Layer selection showing while play testing

### ISSUE THREAD

**Issue by ImShibaGames** [HJfod/BetterEdit#139] opened 2024-02-11 09:19 UTC
**Bug description**
A clear and concise description of what the bug is - is something not working as expected? Does something look off? Is the mod conflicting with another mod?

**Screenshots**
If you have screenshots / videos, please include them!

**Platform**
 * [ ] Windows
 * [ ] Mac
 * [✓
![Screenshot_2024-02-11-17-19-14-06_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/HJfod/BetterEdit/assets/122205012/41c296ae-0feb-489c-8b3a-9e8bab59267b)
] Android (32-bit)
 * [ ] Android (64-bit)
 * [ ] Linux

**Comment by enderprism** [comment] 2024-02-11 09:29
Duplicate of #117

**Closed as completed** 2024-02-11 09:30 UTC
Labels: bug
