### ISSUE TITLE
Add Objects as Favorites

### ISSUE THREAD

**Issue by Yoss2003** [HJfod/BetterEdit#186] opened 2024-02-14 16:38 UTC
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/2cec62bc-d984-4557-981f-759a88606d83">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa">
    <img alt="GitHub Octicons: Beaker" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa" margin="0px">
  </picture>
  Suggestion
  <br />
</h1>
Suggest a new feature to be added.
<hr />

### How should it work?
It would work if in the "edit color" or "edit group" section the option to "add to favorites" is added and these objects are added to an additional tab (next to the "C" tab) with the icon of a heart or a star and the objects that we have marked as favorites are stored.

### What does it look/sound/act like?
It would look like the heart of adding to favorites and would be positioned in the "Edit Color" or "Edit Group" tabs where you see fit.

### What is its purpose?
The purpose of this mod is to be able to speed up the creation process with objects that are used more frequently, either with objects or triggers, so that you don't spend a lot of time walking through the pages of the editor.

**Comment by HJfod** [comment] 2024-02-15 15:22
duplicate of #152

**Closed as completed by HJfod** 2024-02-15 15:22 UTC
Labels: suggestion
