### ISSUE TITLE
Layer number is not removed during playtest

### ISSUE THREAD

**Issue by thekenry** [HJfod/BetterEdit#137] opened 2024-02-11 08:33 UTC
![20240211112838_1](https://github.com/HJfod/BetterEdit/assets/129413254/697ac644-369c-48a1-8c27-c7839477a8a9)

Layer number is not removed during playtest

**Comment by enderprism** [comment] 2024-02-11 09:29
Duplicate of #117

**Closed as completed** 2024-02-11 09:29 UTC
Labels: bug
