### ISSUE TITLE
The button that shows (and lets you select) layers doesn't disappear when playtesting

### ISSUE THREAD

**Issue by JustLudwig** [HJfod/BetterEdit#122] opened 2024-02-10 23:18 UTC
When playtesting, the layer button doesn't disappear with the rest of the ui

**Platform**
 * [ ] Android (64-bit)

**Screenshots**
If you have screenshots / videos, please include them!
![Screenshot_20240210-201518](https://github.com/HJfod/BetterEdit/assets/139890389/1f1bb605-46da-4b7e-881a-4db40e6db8bc)

**Comment by HJfod** [comment] 2024-02-10 23:33
Duplicate of #117

**Closed as not planned** 2024-02-10 23:34 UTC
Labels: bug
